### ISSUE TITLE
Flask example view function error

### ISSUE THREAD

**Issue by fnokeke** [Pegase745/sqlalchemy-datatables#90] opened 2017-04-22 19:54 UTC
For some reason, flask_tut has view function error: 

`AssertionError: View function mapping is overwriting an existing endpoint function: home`

This error typically happens when views have the same name but none of the views share the same name. In fact, I noticed that the server won't start with any view added in `__init__.py`. 

I tried changing changing the names of view but the server only runs when all the views are commented out.

Any tips?

**Comment by Pegase745** [comment] 2017-04-22 20:41
Looks like you're right ! Have you tried with a newer virtualenv ? I don't really know much more about Flask but will try to look at it. @tdamsma any idea on this ?

**Comment by fnokeke** [comment] 2017-04-22 21:08
Been at it for some time now. Tried new virtualenv but still no luck.

**Comment by tdamsma** [comment] 2017-04-23 18:06
Ok, so the issue is that the app is defined in the models.py as `app = Flask(__name__)`. If you move this to the `__init__.py` this solves the routing issues. Unfortunately, there is now a circula dependency where you need to import the app from the __init__.py in the models.py, and import the User and Address from the models.py in the __init__.py. This is as always discussed on [SO](http://stackoverflow.com/questions/34281873/how-do-i-split-flask-models-out-of-app-py-without-passing-db-object-all-over), but I haven't found a nice example implementation yet. Perhaps it would be sufficient for the example to combine everything in one file?

**Comment by tdamsma** [comment] 2017-04-23 18:29
More info on how to structure the example: http://flask.pocoo.org/docs/0.12/patterns/packages/

**Comment by Pegase745** [comment] 2017-04-23 18:52
Nice catch. We'll just have to keep it simple as it is only an example app
that's lighter than the pyramid one

**Comment by tdamsma** [comment] 2017-04-23 18:56
I am now fiddling with splitting the app, almost there. Am boarding in 5 mins, will commit it when I land. If it gets too messy, then I'll try an all in one version. Or maybe we should revert to you original working example?

**Comment by fnokeke** [comment] 2017-04-23 20:17
Made some progress. 

Import directly from `models` in line 6 of `__init__.py from`. Precisely, change 
`from flask_tut.models import` to `from models import` and it works.

**Comment by tdamsma** [comment] 2017-04-24 07:27
See here for some ideas;: 

https://github.com/tdamsma/sqlalchemy-datatables/tree/flask_example_update
https://github.com/tdamsma/sqlalchemy-datatables/tree/flask_example_split_code

In one branch I splitted the code over several files, in the other I merged it all in one

**Comment by saifraider** [comment] 2017-04-25 11:01
If you would like to see the working structured application of flask using postgres, Jquery, Ajax, CSS, JS, etc. for full stack web development python, take a look at https://github.com/saifraider/FullStackPython

**Closed** 2017-05-16 13:26 UTC
Labels: bug, examples
